#!/bin/sh

/bin/busybox --install -s /bin/
/bin/busybox --install -s /sbin/

#Mount things needed by this script
mount -t proc proc /proc
mount -t sysfs sysfs /sys

#Disable kernel messages from popping onto the screen
#echo 0 > /proc/sys/kernel/printk

#Clear the screen
#clear

#Create device nodes
mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

#This will only be run if the exec above failed
echo "Failed to switch_root, dropping to a shell"
exec sh
